from pydantic import BaseModel, Field

class RecipeRequest(BaseModel):
    image_base64: str = Field(..., description="The food image converted to a base64 string")

class RecipeResponse(BaseModel):
    recipe: str = Field(..., description="The recipe generated by the Vision Model")
